<?php
//--- This code is generated by ProBot ---
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Jakat;
use App\Models\Brunch;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class JakatController extends Controller{

	public function index(){
		$brunchs=Brunch::all();

		$jakats=Jakat::paginate(10);
		return view("pages.erp.jakat.index_jakat",["jakats"=>$jakats,"brunchs"=>$brunchs]);
	}
	public function create(){
		$brunchs=Brunch::all();

		return view("pages.erp.jakat.create_jakat",["brunchs"=>$brunchs]);
	}
	public function store(Request $request){
//		Jakat::create($request->all());
		$jakat=new Jakat;
		$jakat->brunch_id=$request->cmbBrunchId;
		$jakat->brunch_name=$request->txtBrunch_name;
		$jakat->donor=$request->txtDonor;
		$jakat->category=$request->txtCategory;
		$jakat->mediam=$request->txtMediam;
		$jakat->amount=$request->txtAmount;
		$jakat->comment=$request->txtComment;

		$jakat->deleted_at=$request->txtDeleted_at;

		$jakat->save();
		return back()->with('success','Created Successfully.');
  
	}
	public function show($id){
		$sjakat=Jakat::find($id);
		return response()->json([
			'status'=>200,
			'sjakat'=>$sjakat
		]);
	}
	public function edit($id){
		$jakat=Jakat::find($id);
		return response()->json([
			'status'=>200,
			'jakat'=>$jakat
		]);
	}

	public function update(Request $request){
//		$jakat->update($request->all());
		$jakatid=$request->input('cmbjakatId');

		$jakat = Jakat::find($jakatid);
		$jakat->id=$request->cmbjakatId;
		$jakat->brunch_id=$request->cmbBrunchId;
		$jakat->brunch_name=$request->txtBrunch_name;
		$jakat->donor=$request->txtDonor;
		$jakat->category=$request->txtCategory;
		$jakat->mediam=$request->txtMediam;
		$jakat->amount=$request->txtAmount;
		$jakat->deleted_at=$request->txtDeleted_at;

		$jakat->update();
		return redirect()->route("jakats.index")->with('success','Updated Successfully.');
    
	}

	
	public function destroy(Request $request){
		
		$jakatid=$request->input('d_jakat');
		$jakat= Jakat::find($jakatid);
		$jakat->delete();


		return redirect()->back()
			   ->with('success',' Deleted successfully');
	}
}
